### ISSUE TITLE
Todo App CRUD API 테스트코드 작성 완료

### ISSUE THREAD

**Issue by sojeongLee0125** [sojeongLee0125/github_test#5]
### 구현 해야하는 기능
구현 완료된 api 테스트 코드 작성 완료

### 구현 전 사전 요구사항
1. [ ] 요구사항 명세서 작성
2. [ ] Api 명세서 작성
3. [ ] 기본 CRUD API 구현 완료.

### 예상 작업 시간
2h
